# Generated by Django 3.0.4 on 2020-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
