# Generated by Django 3.0.4 on 2020-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote101',
            fields=[
                ('quote_number', models.IntegerField(primary_key=True, serialize=False)),
                ('quote_customer', models.CharField(max_length=200)),
                ('quote_address', models.CharField(max_length=200)),
                ('quote_employee', models.CharField(max_length=200)),
                ('quote_totoal_price', models.CharField(max_length=200)),
                ('quote_items_code', models.CharField(max_length=2000)),
            ],
        ),
    ]
