# Generated by Django 3.0.4 on 2020-04-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote101',
            new_name='Quote202',
        ),
    ]
