# Generated by Django 3.0.5 on 2020-04-15 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200329_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_auto_20200403_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote202',
            name='quote_items_code',
        ),
        migrations.AddField(
            model_name='quote202',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quote202',
            name='quote_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote202',
            name='quote_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quote_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='quote202',
            name='quote_items',
            field=models.ManyToManyField(to='quotes.Quote_item'),
        ),
    ]
